.TH LIBHAIKU 7 LIBHAIKU
.SH NAME
libhaiku \- Poetic error messages
.SH DESCRIPTION
.B libhaiku
is an API on top of a collection of haiku, that lets a programmer
make a program print haiku for error messages. Instead of calling
.BR perror (3),
the program should call
.BR libhaiku_perror (3).
.SH "SEE ALSO"
.BR libhaiku_perror (3),
.BR perror (3)
.SH "KNOWN ISSUES"
Must of the haiku uses 5\-7\-5 syllables rather than 5\-7\-5 morae.
This is however of lesser importance, as it is much harder to write
a 5\-7\-5 mora haiku than a 5\-7\-5 syllable haiku.
.SH LICENSE
Copyright \(co 2016  Mattias Andrée
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.PP
Copying and distribution of this manual, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.
.SH BUGS
Please report bugs to <https://github.com/maandree/libhaiku/issues>
or to <maandree@member.fsf.org>.

